apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
  - ovms-ootb.yaml
  - caikit-ootb.yaml
  - tgis-ootb.yaml
  - ovms-kserve-ootd.yaml
images:
  - name: ovms-1
    newName: quay.io/opendatahub/openvino_model_server
    digest: sha256:ccfce13c89c4ddfd31e6c56fc35fd46afe10c2d3d3998ab1c2bf14448fdd389f
  - name: caikit-tgis-serving
    newName: quay.io/opendatahub/caikit-tgis-serving
    digest: sha256:fdec8839a5599b38dd0f3565c8f66f0c859d4267d2d58cffba6e7883594b7cdd
  - name: text-generation-inference
    newName: quay.io/opendatahub/text-generation-inference
    digest: sha256:66071edb8a76cb5949bf8f0b8af6f53810e66a5ef5e4388fd78f74cc155f83a5
  - name: ovms-kserve
    newName: quay.io/modh/openvino_model_server
    digest: sha256:007304a96acd654ca5133c50990c6785464fcea44304c8a846d3279b9c83a9d4
